import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";
import AuthHydrateProvider from "@/components/AuthHydrateProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Footer() {
  return (
    <footer
      style={{
        padding: "20px",
        background: "#141414",
        color: "#fff",
        textAlign: "center",
      }}
    >
      © {new Date().getFullYear()} Netflix Clone
    </footer>
  );
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AuthHydrateProvider>
          <NavBar />
          <main style={{ paddingTop: "80px", minHeight: "80vh" }}>
            {children}
          </main>
          <Footer />
        </AuthHydrateProvider>
      </body>
    </html>
  );
}